// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package meta

import (
	"github.com/wasya-io/petit-misskey/config"
	"github.com/wasya-io/petit-misskey/infrastructure/bubbles"
	"github.com/wasya-io/petit-misskey/infrastructure/misskey"
	"github.com/wasya-io/petit-misskey/infrastructure/setting"
	"github.com/wasya-io/petit-misskey/service/meta"
)

// Injectors from wire.go:

func InitializeModel(instance *setting.Instance) *Model {
	configConfig := config.NewConfig()
	client := misskey.NewClient(configConfig, instance)
	service := meta.NewService(client)
	viewportFactory := bubbles.NewViewportFactory()
	model := NewModel(service, viewportFactory)
	return model
}
